### ISSUE TITLE
Load fonts

### ISSUE THREAD

**Issue by doczoidberg** [zefoy/ngx-font-picker#10]
How can I change a font on page load?

The change event does load the font? How can I trigger it on page load?

(I have different fonts on a page which i've set before)

**Comment by sconix** [comment]
I am not sure I follow you. So do you mean that the selected font changes outside of the font-picker and you would like to trigger the font loading? At the moment the dialog only loads the selected font on init, but I think I should change it so that it loads the font automatically when ever changed (with optional input to disable this behavior). So if this is what you need I could add this to next release which I might already do tomorrow.

**Comment by sconix** [comment]
I just released 5.1.0 that supports auto loading of the font when the input changes. So if this was what you were after its now possible. There is also public API for loading fonts manually.

**Comment by doczoidberg** [comment]
I solved my problem with webfontloader.
