### ISSUE TITLE
Styling the font picker

### ISSUE THREAD

**Issue by HeadwayLabs** [zefoy/ngx-font-picker#11]
I am integrating the color picker into my application and want to make substantial style changes to it. In particular I am making a dark theme for it.

What is the best way to achieve this? I'd like to exclude the css from the color picker in node modules and then include it in my own SCSS file in my app. This is so I don't loose changes if I upgrade and secondly to make sure I don't duplicate and override css.

If I delete the css in the main css file the syles still show. Any ideas or alternative suggestions?

**Comment by sconix** [comment]
Styles are inlined so its not that easy to get rid of them unless you have custom build system. So you just need to override the style in normal manner and I don't see it being that bad. Its not like the styles take a lots of space and overriding them wont be any more prone for breakage than replacing them. Its a bitty that there is no dynamic theme system in Angular.

**Comment by HeadwayLabs** [comment]
Thanks for the suggestions. The problem with overriding the styles is it cause loads of specificity issues. This is because angular uses the [_ngcontent-c10] to make the css very specific to that component.

The only way to overcome this is to add a ridiculously long selector or use !important.. both ugly solutions.

Is there no way to add a config to the inlining to turn it on and off?

**Comment by sconix** [comment]
Oh it seems that I have forgot to turn the style encapsulation off for the dialog component. There is no point having the style encapsulation on for this type of component so I will make a new release soon with the encapsulation turned off. This should help and make the custom styling more easy.

The libraries are usually provided as styles inlined so only option would be to ship with and without which wont make sense since there is no standard support for such thing.

**Comment by sconix** [comment]
There is now 5.2.0 release out that does not have the style encapsulation so this should make custom styling easier. Let me know if it is not enough and I can re-open this issue although not sure what other options there would be to fix this.

**Comment by HeadwayLabs** [comment]
Thanks, I appreciate your assistance, I will give this a try.
